"""Create distribution resources table

Revision ID: 6074f7c90df0
Revises: f3fabc77e76a
Create Date: 2026-07-15 12:01:07.611707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6074f7c90df0'
down_revision: Union[str, Sequence[str], None] = 'f3fabc77e76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distribution_event_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distribution_event_id'], ['distribution_events.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_resources_id'), 'distribution_resources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_resources_id'), table_name='distribution_resources')
    op.drop_table('distribution_resources')
    # ### end Alembic commands ###
