"""Create distribution verifications table

Revision ID: 82e24bad465a
Revises: 6074f7c90df0
Create Date: 2026-07-27 13:13:46.313371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e24bad465a'
down_revision: Union[str, Sequence[str], None] = '6074f7c90df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distribution_event_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=False),
    sa.Column('verification_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['distribution_event_id'], ['distribution_events.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_verifications_id'), 'distribution_verifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_verifications_id'), table_name='distribution_verifications')
    op.drop_table('distribution_verifications')
    # ### end Alembic commands ###
