"""Initial schema

Revision ID: f60e4156946a
Revises: ed6f59b5e1b2
Create Date: 2026-07-09 15:02:24.870301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60e4156946a'
down_revision: Union[str, Sequence[str], None] = 'ed6f59b5e1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('households', 'household_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('vulnerability_assessments', sa.Column('assessment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerability_assessments', 'assessment_date')
    op.alter_column('households', 'household_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
